name: CI Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run tests
        run: echo ES_NODE_CONTRACT_ADDRESS=`0x5C935469C5592Aeeac3372e922d9bCEabDF8830d` >> "$GITHUB_ENV"

      - name: Notify on Slack
        if: always()  # 无论成功或失败，始终发送通知
        uses: slackapi/slack-github-action@v1.23.0
        with:
          slack-message: |
            工作流 ${{ github.workflow }} 已完成。
            状态: ${{ job.status }}
            触发者: ${{ github.actor }}
            仓库: ${{ github.repository }}
            Contract: $ES_NODE_CONTRACT_ADDRESS
            Contract1: ${{ ES_NODE_CONTRACT_ADDRESS }}
            Contract2: ${{ $ES_NODE_CONTRACT_ADDRESS }}

        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}


