name: CI Workflow

on: [push]

jobs:
  send_notification:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run your tests or actions
        run: |
          # 这里执行一些任务并生成结果文件
          echo "Test Output" > result.txt

      - name: Upload artifact for attachment
        uses: actions/upload-artifact@v4
        with:
          name: result-log
          path: result.txt  # 上传 result.txt 文件作为 artifact

      - name: Notify Slack with result
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}  # Slack Incoming Webhook URL
          SLACK_CHANNEL: general
          SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'
          SLACK_ICON: https://github.com/rtCamp.png?size=48
          SLACK_MESSAGE: 'Post Content :rocket:'
          SLACK_TITLE: Post Title
          SLACK_USERNAME: rtCamp
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}


      - name: Clean up
        run: |
          rm result.txt  # 删除生成的日志文件


